digraph dependencies {

   graph [
      label="Generated by Oraculum"
      labeljust=l
      nodesep=0.2
      ranksep=0.3
      fontname=Helvetica
      fontsize=7
   ];

   node [
      shape=rectangle
      height=0.2 
      fontname=Helvetica
      fontsize=8
   ];

<#if draw_parents == true>
   <#list package.parents as parent>
       <#if parent.name != package.name>
   "${parent.name}" -> "${package.name}"
       </#if> 
   </#list>
</#if>

<#if draw_childen == true>
   <#list package.children as child>
       <#if package.name != child.name>
   "${package.name}" -> "${child.name}"
       </#if> 
   </#list>
</#if>
   
}