digraph "schema" { 

   graph [
      rankdir=LR
      label="Generated by Oraculum"
      labeljust=l
      nodesep=0.2
      ranksep=0.5
      fontname=Helvetica
      fontsize=7
   ];

   node [
      fontname=Helvetica
      fontsize=9
      shape=plaintext
   ];

   edge [
      arrowsize="0.7"
   ];

<#list tables as table>
   <#list table.columns as column>
      <#list column.foreignKeys as key>
         <#if key.ignored == false>
   "${table.name}":"${column.name}.type":e -> "${key.table}":"${key.column}":w;
         </#if>
      </#list>
   </#list>
</#list>

<#list tables as table>
   "${table.name}" [label=<
   <TABLE BGCOLOR="#FFD873" BORDER="0" CELLBORDER="1" CELLSPACING="0">
      <TR>
         <TD ALIGN="CENTER" PORT="HEADER" BGCOLOR="#FFB800" COLSPAN="2">${table.name?upper_case}</TD>
      </TR>
<#list table.columns as column>
   <#if column.ignored == false>
      <TR>
         <TD ALIGN="LEFT" PORT="${column.name}" <#if column.primary>BGCOLOR="#FFCA40"</#if>>${column.name}</TD>
         <TD PORT="${column.name}.type" <#if column.primary>BGCOLOR="#FFCA40"</#if>>${column.type}</TD>
      </TR>
   </#if>
</#list>
   </TABLE>>];

</#list>
}