#
# ${config.name} Properties
#
# This file was generated by Configo 
# (http://code.google.com/workingonit/ConfigoProject)
#

<#list config.modules as module>
# ---------------------------------------------------------
# ${module.name}
#
# <@defaultString value="${module.description!'No description'}"/>

<#list module.properties as property>
# <@defaultString value="${property.name!''}"/>
# <@defaultString value="${property.description!''}" default="no description available"/>
${property.key} = <@defaultString value="${property.value!''}"/>
</#list>

</#list>
